[features]
seeds = false
[programs.devnet]
metaplex_anchor_nft = "DTC2Tw5hNfQGMGeRHxyC6c7bWaMu33rUh9CTgDEMbDn3"

[registry]
url = "https://devnet.sonic.game/"
[provider]
cluster = "https://devnet.sonic.game/"
wallet = "./wallet1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/initialize.ts"
initialize = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/initialize.ts"